# Generated by Django 6.0 on 2025-12-09 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nominativi', models.TextField(verbose_name='Nominativi degli accessi')),
                ('ditta', models.CharField(max_length=100, verbose_name='Ditta')),
                ('oraIngresso', models.DateTimeField(verbose_name='Ora di ingresso')),
                ('oraUscita', models.DateTimeField(blank=True, null=True, verbose_name='Ora di uscita')),
            ],
            options={
                'verbose_name_plural': 'Accessi',
            },
        ),
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True, verbose_name='Data di caricamento')),
                ('data_riferimento', models.DateField(verbose_name='Data di riferimento della fattura')),
                ('file', models.FileField(upload_to='fatture/%Y/%m_%B/', verbose_name='File della fattura')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione della fattura')),
            ],
            options={
                'verbose_name_plural': 'Fatture',
            },
        ),
        migrations.CreateModel(
            name='Impostazioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Token del bot Telegram')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, verbose_name='Chat ID Telegram')),
                ('debug', models.BooleanField(default=False, verbose_name='Modalità debug')),
            ],
            options={
                'verbose_name_plural': 'Impostazioni generali',
            },
        ),
        migrations.CreateModel(
            name='PersonaleINAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominativo', models.CharField(max_length=100, unique=True, verbose_name='Nominativo completo')),
                ('nomeutente', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nome utente INAF')),
            ],
            options={
                'verbose_name_plural': 'Personale INAF',
            },
        ),
        migrations.CreateModel(
            name='ReportGiornaliero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_riferimento', models.DateField(unique=True)),
                ('pdf', models.FileField(upload_to='reports/%Y/%m_%B/')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Report giornalieri',
            },
        ),
        migrations.CreateModel(
            name='Turni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_caricamento', models.DateTimeField(auto_now_add=True, verbose_name='Data di caricamento')),
                ('data_riferimento', models.DateField(verbose_name='Data di riferimento della programmazione')),
                ('file', models.FileField(upload_to='turni/%Y/%m_%B/', verbose_name='File della programmazione turni')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione della programmazione')),
            ],
            options={
                'verbose_name_plural': 'Programmazioni turni',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('azione', models.TextField(verbose_name='Log')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='È attualmente presente?')),
                ('personale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personaleinaf', verbose_name='Personale INAF')),
            ],
            options={
                'verbose_name_plural': 'Presenze del personale INAF',
            },
        ),
        migrations.CreateModel(
            name='RegistroGiornaliero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data del registro')),
                ('note', models.TextField(blank=True, verbose_name='Note della giornata')),
                ('accessi', models.ManyToManyField(blank=True, related_name='registri_giornalieri', to='core.accesso', verbose_name='Accessi del giorno')),
                ('personale', models.ManyToManyField(blank=True, related_name='registri_giornalieri', through='core.Presenza', to='core.personaleinaf', verbose_name='Personale presente')),
            ],
            options={
                'verbose_name_plural': 'Registri giornalieri',
            },
        ),
        migrations.AddField(
            model_name='presenza',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registrogiornaliero', verbose_name='Registro giornaliero'),
        ),
        migrations.CreateModel(
            name='TurnoVigilanza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('orario_inizio', models.DateTimeField(verbose_name='Orario di inizio')),
                ('orario_fine', models.DateTimeField(blank=True, null=True, verbose_name='Orario di fine')),
                ('data', models.DateField(verbose_name='Data del turno')),
                ('vigilante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vigilante')),
            ],
            options={
                'verbose_name_plural': 'Turni di vigilanza',
            },
        ),
        migrations.AddField(
            model_name='registrogiornaliero',
            name='turni',
            field=models.ManyToManyField(blank=True, related_name='registri_giornalieri', to='core.turnovigilanza', verbose_name='Turni del giorno'),
        ),
        migrations.AddField(
            model_name='accesso',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turnovigilanza', verbose_name='Turno di vigilanza'),
        ),
        migrations.AlterUniqueTogether(
            name='presenza',
            unique_together={('registro', 'personale')},
        ),
    ]
