# Generated by Django 6.0 on 2025-12-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMensile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_riferimento', models.DateField()),
                ('pdf', models.FileField(upload_to='reports/mensili/%Y/')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
