# Generated by Django 6.0 on 2025-12-09 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reportmensile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportmensile',
            options={'verbose_name_plural': 'Report mensili'},
        ),
    ]
